### ISSUE TITLE
Feature request: The conversion of properties and yaml should be a relatively common function

### ISSUE THREAD

**Issue by meiMingle** [jonathanlermitage/ij-ilove-devtoys#4]

**Comment by jonathanlermitage** [comment]
Good idea.  
It's easy for regular properties files, but it will be a bit tricky for Spring properties, per example for Spring profiles support. Example:
```
                logging.file.name=myapplication.log
                xxx.property=health, info, refresh, shutdown, selftest, listProcessors, foo, bar
                #---
                spring.config.activate.on-profile=dev
                spring.datasource.password=password
                spring.datasource.url=jdbc:h2:dev
                spring.datasource.username=SA
                xxx.property=devValue
                #---
                spring.config.activate.on-profile=prod
                spring.datasource.password=password
                spring.datasource.url=jdbc:h2:prod
                spring.datasource.username=prodUser
                xxx.property=prodValue
```
becomes
```
                logging:
                    file:
                        name: myapplication.log
                xxx:
                    property: health, info, refresh, shutdown, selftest, listProcessors, foo, bar
                ---
                spring:
                    config:
                        activate:
                            on-profile: dev
                    datasource:
                        password: password
                        url: jdbc:h2:dev
                        username: SA
                xxx:
                    property: devValue
                ---
                spring:
                    config:
                        activate:
                            on-profile: prod
                    datasource:
                        password: password
                        url: jdbc:h2:prod
                        username: prodUser
                xxx:
                    property: prodValue
``` 
Every profile is separated by a "---" comment line, which allows duplicated keys.

I developed something for regular and Spring properties (I will let the user select between regular and Spring mode), but I'm wondering if other frameworks need additional support... At least, I will publish this first implementation and I will see if somebody opens a new issue 😁
